[package]
name = "credman"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
rand = "0.9.2"
rand_chacha = "0.9.0"

[dependencies.rusqlite]
version = "0.38.0"
features = ["bundled-sqlcipher"]
